---
permalink: rhel-install/concept_unsupported_features_for_wfa_on_linux.html
sidebar: sidebar
keywords: oncommand, workflow, automation, limitations
summary: "OnCommand Workflow Automation (WFA) 5.1 includes some limitations and unsupported features that you should be aware of before you install and configure WFA."
---
= Known limitations for OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Workflow Automation (WFA) 5.1 includes some limitations and unsupported features that you should be aware of before you install and configure WFA.

* *LDAP authentication*
 ** You can use only Microsoft Active Directory Lightweight Directory Access Protocol (LDAP) server for LDAP authentication.
 ** You must be a member of an LDAP group in order to use LDAP authentication.
 ** You must not use an LDAP user name that is part of a hierarchical structure of multiple domains for authentication or notification.

[NOTE]
====
Microsoft Active Directory Lightweight Directory Services (AD LDS) is not supported.
====
* *WFA data sources types*
+
OnCommand Unified Manager 6.0, 6.1, and 6.2 data source types are deprecated in the WFA 4.1 release, and these data source types will not be supported in future releases.

* *WFA installed on Linux*
 ** Certified content from Data ONTAP operating in 7-Mode is currently not available.
 ** Commands that include only PowerShell code are not compatible with Linux.
 ** Certified commands for7-Mode and VMware are currently not ported to Perl, and are therefore not compatible with Linux.
* *Creating category names*
 ** When a hyphen (-) is used in a category name, it is replaced with a space once the category is saved. For example, if the category name "abc-xyz" is provided, the category name is saved as "abc xyz", with the hyphen removed. To avoid this issue, do not use hyphens in category names.
 ** When a colon (:) is used in a category name, the text string before the colon is ignored once the category is saved. For example, if the category name "abc : xyz" is provided, the category name is saved as "xyz", with the"abc" string removed. To avoid this issue, do not use colons in category names.
 ** There is no check to prevent two categories having the same name. However, this causes a problem when selecting these categories from the navigation pane. To avoid this issue, make sure that each category name is unique.
