---
permalink: rhel-install/task_upgrading_openjdk_on_linux_wfa.html
sidebar: sidebar
keywords: OnCommand Workflow Automation
summary: 'Oracle JRE is no longer supported in OnCommand Workflow Automation. In this release, OpenJDK replaces Oracle JRE for Linux. You can upgrade to a newer version of OpenJDK on the Linux server on which OnCommand Workflow Automation is installed to obtain fixes for security vulnerabilities.'
---
= Upgrading OpenJDK
:icons: font
:imagesdir: ../media/

[.lead]
Oracle JRE is no longer supported in OnCommand Workflow Automation. In this release, OpenJDK replaces Oracle JRE for Linux. You can upgrade to a newer version of OpenJDK on the Linux server on which OnCommand Workflow Automation is installed to obtain fixes for security vulnerabilities.

You must have root privileges for the Linux system on which WFA is installed.

You can update OpenJDK releases within release families. For example, you can upgrade from OpenJDK 11.0.1 to OpenJDK 11.0.2, but you cannot update directly from OpenJDK 11 to OpenJDK 12.

. Log in as a root user on the WFA host machine.
. Install the latest version of OpenJDK 11 from the yum repository on the target system.
. At the shell prompt, stop the WFA server.
. Restart the WFA server.
