---
permalink: rhel-install/task-replace-the-default-workflow-automation-ssl-certificate-linux.html
sidebar: sidebar
keywords: replace, default, workflow, automation, ssl, certificate
summary: "You can replace the default Workflow Automation (WFA) SSL certificate if the certificate has expired or if you want to increase the validity period of the certificate."
---
= Replace the default Workflow Automation SSL certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can replace the default Workflow Automation (WFA) SSL certificate if the certificate has expired or if you want to increase the validity period of the certificate.

You must have root privileges for the Linux system on which you have installed WFA.

The default WFA installation path is used in this procedure. If you changed the default location during installation, you must use the custom WFA installation path.

.Steps
. Log in as a root user on the WFA host machine.
. At the shell prompt, navigate to the following directory on the WFA server: WFA_install_location/wfa/bin
. Stop the WFA database and server services:
+
`./wfa --stop=WFA`
+
`./wfa --stop=DB`
. Delete the wfa.keystore file from the following location: WFA_install_location/wfa/jboss/standalone/configuration/keystore.
. Open a shell prompt on the WFA server, and then change directories to the following location: <OpenJDK_install_location>/bin
. Obtain the database key:
+
`keytool -keysize 2048 -genkey -alias "ssl keystore" -keyalg RSA -keystore "WFA_install_location/wfa/jboss/standalone/configuration/keystore/wfa.keystore" -validity xxxx`
+
xxxx is the number of days for the validity of the new certificate.

. When prompted, provide the password (default or new).
+
The default password is a randomly generated encrypted password.
+
To obtain and decrypt the default password, use the steps in the Knowledge Base article link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F[How to renew the self-signed certificate on WFA 5.1.1.0.4^]

. Enter the required details for the certificate.
. Review the displayed information, and then enter `Yes`.
. Press *Enter* when prompted by the following message: Enter key password for <SSL keystore> <RETURN if same as keystore password>.
. Restart the WFA services:
+
`./wfa --start=DB`
+
`./wfa --start=WFA`

// BURT 1498856, 2022-09-01
