---
settings:
  name: Workflow Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: OnCommand Workflow Automation Documentation
      url: "/index.html"
    - section: help
    - section: workflow
    - title: Legal notices
      url: "/reference-legal-notices.html"
