---
settings:
  name: OnCommand Workflow Automation 5.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: OnCommand Workflow Automation 5.1 docs
      url: "/index.html"
    - title: Release notes
      url: "/reference-releasenotes.html"
    - section: rhel-install
    - section: windows-install
    - section: workflow
    - section: help
    - title: Legal notices
      url: "/reference-legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release Notes
          url: reference-releasenotes.html
    - title: Install and setup
      links:
        - title: Install OnCommand Workflow Automation on Linux systems
          url: rhel-install/concept-oncommand-workflow-automation-installation-and-configuration-instructions.html
        - title: Install OnCommand Workflow Automation on Windows
          url: windows-install/concept-oncommand-workflow-automation-installation-and-configuration-instructions.html
    - title: Build and manage workflows
      links:
        - title: Managing workflows
          url: workflows/concept-managing-workflows.html

