---
settings:
  name: OnCommand Workflow Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: OnCommand Workflow Automation Docs
      url: "/index.html"
    - title: Release Notes
      url: "/reference-releasenotes.html"
    - section: rhel-install
    - section: windows-install
    - section: workflow
    - section: help
    - title: Legal notices
      url: "/reference-legal-notices.html"
