---
permalink: windows-install/reference_system_requirements_for_oncommand_workflow_automation_windows.html
sidebar: sidebar
keywords: OnCommand Workflow Automation
summary: 'You must be aware of the OnCommand Workflow Automation \(WFA\) hardware and software requirements before installing WFA.'
---
= System requirements for installing OnCommand Workflow Automation
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the OnCommand Workflow Automation (WFA) hardware and software requirements before installing WFA.

== Hardware requirements for installing WFA

The following table lists the minimum hardware requirements and the recommended hardware specifications for the WFA server.

|===
| Component| Minimum requirements| Recommended specifications
a|
CPU
a|
2.27 GHz or faster, 4 core, 64-bit
a|
2.27 GHz or faster, 4 core, 64-bit
a|
RAM
a|
4 GB
a|
8 GB
a|
Free disk space
a|
5 GB
a|
20 GB
|===
If you are installing WFA on a virtual machine (VM), you should reserve the required memory and CPU so that the VM has sufficient resources. The installer does not verify the CPU speed.

== Software requirements for installing WFA

WFA runs on a 64-bit Windows operating system, and should be installed on dedicated physical machines or VMs. You must not install any other application on the server that runs WFA.

WFA runs from Microsoft Windows Server 2012 Enterprise Edition to Microsoft Windows Server 2016 (all editions). Enterprise Edition is the recommended Windows operating system.

For Windows 2012 servers, .NET Framework version 4.5.2 must be installed on your Windows system. If .NET Framework version 4.5.2 is not installed, WFA 5.1 installation fails.

* One of the following supported browsers:
 ** Mozilla Firefox
 ** Microsoft Internet Explorer
 ** Google Chrome
* PowerShell 3.0
* VMware PowerCLI version 5
+
NOTE: The PowerShell extension for VMware APIs is required only if you are using WFA to execute workflows on VMware vSphere.

NOTE: Antivirus applications might prevent WFA services from starting.

To avoid this issue, configure antivirus scanning exclusions for the following WFA directories:

* The directory where you have installed WFA
* The directory where you have installed Perl
* The directory where you have installed OpenJDK
* The MySQL Data Directory

For more details, see the https://mysupport.netapp.com/matrix[Interoperability Matrix Tool].

*Related information*

xref:reference_ports_required_for_oncommand_workflow_automation.adoc[Ports required for Workflow Automation]

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
