---
permalink: windows-install/task-configure-wfa-with-mscs-using-configuration-scripts.html
sidebar: sidebar
keywords: configure, workflow, automation, mscs
summary: "After you install Workflow Automation (WFA) in Microsoft Cluster Server (MSCS), you must configure WFA for high availability in MSCS using configuration scripts."
---
= Configure Workflow Automation with MSCS
:icons: font
:imagesdir: ../media/

[.lead]
After you install Workflow Automation (WFA) in Microsoft Cluster Server (MSCS), you must configure WFA for high availability in MSCS using configuration scripts.

You must have created a backup of WFA.

NOTE: Before you start your configuration make sure that the WFA encryption key is set consistently on both MSCS cluster nodes. If it is not set on both nodes, then when failover occurs, the credentials cannot be decrypted on the second node causing workflow failures.

.Steps
. Log in to the first node of the MSCS cluster, and perform the following steps:
+
[cols="2*",options="header"]
|===
| For...| Do this...
a|
Windows 2012, Windows 2016, Windows 2019
a|

 .. From the Failover Cluster Manager, right-click *Service Roles*.
 .. Select *Create Empty Service Role*, and then rename the role to "`WFA`".
 .. Add the IP address resource to the newly created "`WFA`" role:
  ... From the Failover Cluster Manager, right-click the newly created "`WFA`" role.
  ... Select *Resource* > *More Resources* > *IP Address*.
  ... Configure the cluster IP address.

+
|===

. Edit the `mscs_data_parameters.xml` file and set the relative path to the MySQL data directory:
+
----
<dir>
    <description>Data directory</description>
    <srcpath>..\..\..\..\..\ProgramData\MySQL\MySQLServerData</srcpath>
    <destpath>wfa</destpath>
</dir>
----

. Edit the `mscs_resource_properties.xml` file and make the following updates:
 .. Perform a find/replace for the `NA_WFA_DB` service name and update it to `MYSQL57`.
 .. Set the `vip_res <prettyname>` to the virtual IP address name:
+
----
<resource>
    <type>essential</type>
    <id>vip_res</id>
    <prettyname>WFA IP address</prettyname>
</resource>
----

 .. Set the `data_res <prettyname>` to the disk name assigned to the share disk resource:
+
----
<resource>
    <type>essential</type>
    <id>datadisk_res</id>
    <prettyname>Cluster Disk 2</prettyname>
</resource>
----

 .. Copy the XML files from the first node to the second node:``copy “\\node1\D$\Program Files\NetApp\WFA\bin\ha\*xml” “D:\Program Files\NetApp\WFA\bin\ha”``
 .. Run the command to join the second node to the cluster:``D:\Program Files\NetApp\WFA\bin\ha>perl ha_setup.pl --join -t mscs -f E:\``
. At the command prompt, run the ha_setup.pl script to move the WFA data to the shared location and to configure WFA with MSCS for failover. The script is available at WFA_install_location\WFA\bin\ha\. `perl ha_setup.pl --first [-t type_of_cluster_vcs] [-g cluster_group_name] [-i IP_address_name] [-n cluster_name] [-k shared_disk_resource_name] [-f shared_drive_path]`
+
The ha_setup.pl script expects an input using the IP Address resource for the MSCS cluster. When installing on MSCS 2016, the resource needs to be added by name, not IP address, `WFA IP address`. For example:
+
`perl ha_setup.pl --first -t mscs -g WFA -i "WFA IP address" -n wfa_cluster -k "Cluster Disk 2" -f E:\`

. Verify that the MSCS resources are created, by checking for the successfully configured message in the output.
+
----
=== Successfully configured MSCS cluster resources on this node ===
----

. Stop the WFA services from the Failover Cluster Manager:
+
[cols="2*",options="header"]
|===
| For...| Do this...
a|
Windows 2012, Windows 2016, Windows 2019
a|

 .. Select *Service Roles*, and then select the newly created "`WFA`" role.
 .. In the Resource pane, right-click *MYSQL57*, and then select *Take Offline*.
 .. In the Resource pane, right-click *NA_WFA_SRV*, and then select *Take Offline*.

+
|===
The WFA database service and the WFA server service must be taken offline. The WFA services must not be stopped from the Windows services.

. Manually move the WFA resources to the secondary node.
. Verify that the shared disk is accessible from the second node.
. At the command prompt, run the ha_setup.pl script on the secondary node of the cluster to configure WFA for using the data from the shared location: `perl ha_setup.pl --join [-t type_of_cluster_mscs] [-f shared_drive_path]`
+
The ha_setup.pl script is available at WFA_install_location\WFA\bin\ha\.
+
`perl ha_setup.pl --join -t mscs -f E:\`

. From the Failover Cluster Manager, bring the WFA resources online:
+
[cols="2*",options="header"]
|===
| For...| Do this...
a|
Windows 2012, Windows 2016, Windows 2019
a|

 .. Right-click the newly created "`WFA`" role, and then select *Start Role*.
 The role must be in the Running status, and the individual resources must be in the Online state.

+
|===

. Manually switch to the second node of the MSCS cluster.
. Verify that the WFA services start properly on the second node of the cluster.
