---
permalink: windows-install/task-replace-the-default-workflow-automation-ssl-certificate.html
sidebar: sidebar
keywords: replace, default, workflow, automation, ssl certificate
summary: "You can replace the default Workflow Automation (WFA) SSL certificate if the certificate has expired or if you want to increase the validity period of the certificate."
---
= Replace the default Workflow Automation SSL certificate
:icons: font
:imagesdir: ../media/

[.lead]
You can replace the default Workflow Automation (WFA) SSL certificate if the certificate has expired or if you want to increase the validity period of the certificate.

You must have Windows admin privileges on the WFA server.

The default WFA installation path is used in this procedure. If you changed the default location during installation, you must use the custom WFA installation path.

.Steps
. Log in as the admin user on the WFA host machine.
. Use the Windows Services console to stop the following WFA services:
 ** NetApp WFA Database
 ** NetApp WFA Server
. Delete the wfa.keystore file from the following location:
+
`<WFA_install_location>\WFA\jboss\standalone\configuration\keystore`
. Open a command prompt on the WFA server, and change directories to the following location:<OpenJDK_install_location>\bin
. Obtain the database key:
+
`keytool -keysize 2048 -genkey -alias "ssl keystore" -keyalg RSA -keystore "<WFA_install_location>\WFA\jboss\standalone\configuration\keystore\wfa.keystore" -validity xxxx`
+
xxxx is the number of days for the new certificate's validity.

. When prompted, provide the password (default or new).
+
The default password is a randomly generated encrypted password.
+
To obtain and decrypt the default password, follow the steps in the Knowledge Base article link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F[How to renew the self-signed certificate on WFA 5.1.1.0.4^]
+
To use a new password, follow the steps in the Knowledge Base article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_update_a_new_password_for_the_keystore_in_WFA[How to update a new password for the keystore in WFA.^]
. Enter the required details for the certificate.
. Review the displayed information, and enter `Yes`.
. Press *Enter* when prompted by the following message: Enter key password for <SSL keystore> <RETURN if same as keystore password>.
. Restart the WFA services by using the Windows Services console.

// BURT 1498856, 2022-09-01
// BURT 1503227, 2022-Oct-06