---
permalink: windows-install/task-configure-snmp-version-3.html
sidebar: sidebar
keywords: snmp Version 3, snmp traps, configure
summary: "You can also configure OnCommand Workflow Automation (WFA) to send Simple Network Management Protocol (SNMP) Version 3 traps about the status of workflow operations."
---
= Configure SNMP Version 3
:icons: font
:imagesdir: ../media/

[.lead]
You can also configure OnCommand Workflow Automation (WFA) to send Simple Network Management Protocol (SNMP) Version 3 traps about the status of workflow operations.

Version 3 offers two additional security options:

* Version 3 with Authentication
+
Traps are sent unencrypted over the network. SNMP management applications, which are configured by the same authentication parameters as SNMP trap messages, can receive traps.

* Version 3 with Authentication and Encryption
+
Traps are sent encrypted over the network. To receive and decrypt these traps, you must configure SNMP management applications with the same authentication parameters and encryption key as the SNMP traps.

.Steps
. Log in to WFA through a web browser as an admin user, and then access the WFA server.
. Click *Settings*, and under *Setup* click *SNMP*.
. Select the *Enable SNMP* check box.
. In the *Version* drop-down list, select one of the following options:
 ** Version 3
 ** Version 3 with Authentication
 ** Version 3 with Authentication and Encryption
. Select the SNMP configuration options that correspond to the specific SNMP Version 3 option you chose in Step 4.
. Enter an IPv4 or IPv6 address or the host name, and the port number of the management host. WFA sends SNMP traps to the specified port number. The default port number is 162.
. In the Notify On section, select one or more of the following check boxes:
 ** Workflow planning started/failed/completed
 ** Workflow execution started
 ** Workflow execution completed successfully
 ** Workflow execution failed/ partially successful
 ** Workflow execution waiting for approval
 ** Acquisition failure
. Click *Send Test Notification* to verify the settings.
. Click *Save*.
