---
permalink: windows-install/task-upgrade-openjdk-on-windows-wfa.html
sidebar: sidebar
keywords: oncommand, workflow, automation, upgrade, openjdk
summary: "Oracle JRE is no longer supported in OnCommand Workflow Automation. In this release, OpenJDK replaces Oracle JRE for Windows. You can upgrade new versions of OpenJDK for OnCommand Workflow Automation (WFA) on the Windows server. You can upgrade to a newer version of OpenJDK to get fixes for security vulnerabilities on the Windows server."
---
= Upgrade OpenJDK
:icons: font
:imagesdir: ../media/

[.lead]
Oracle JRE is no longer supported in OnCommand Workflow Automation. In this release, OpenJDK replaces Oracle JRE for Windows. You can upgrade new versions of OpenJDK for OnCommand Workflow Automation (WFA) on the Windows server. You can upgrade to a newer version of OpenJDK to get fixes for security vulnerabilities on the Windows server.

You must have Windows admin privileges on the WFA server.

You can update OpenJDK releases within release families. For example, you can upgrade from OpenJDK 11.0.1 to OpenJDK 11.0.2, but you cannot update directly from OpenJDK 11 to OpenJDK 12.

.Steps
. Log in as an admin user on the WFA host machine.
. Download the latest version of OpenJDK 11 (64-bit) to the target system.
. Use the Windows Services console to stop the WFA server and WFA Database services.
. Extract the downloaded version of OpenJDK 11 to the folder where you have installed open JDK.
. Use the Windows Services console to start the WFA services.
