---
permalink: windows-install/task-configure-a-database-user-by-running-ocsetup-on-windows.html
sidebar: sidebar
keywords: configure, database, user, run, ocsetup, windows
summary: "You can run the ocsetup file on the DataFabric Manager 5.x server to configure read-only access of the DataFabric Manager 5.x database to OnCommand Workflow Automation."
---
= Configure a database user by running ocsetup on Windows
:icons: font
:imagesdir: ../media/

[.lead]
You can run the ocsetup file on the DataFabric Manager 5.x server to configure read-only access of the DataFabric Manager 5.x database to OnCommand Workflow Automation.

.Steps
. Download the wfa_ocsetup.exe file to a directory in the DataFabric Manager 5.x server from the following location: _https_://WFA_Server_IP/download/wfa_ocsetup.exe.
+
_WFA_Server_IP_ is the IP address (IPv4 or IPv6 address) of your WFA server.
+
If you have specified a non-default port for WFA, you must include the port number as follows: _https_://wfa_server_ip:port/download/wfa_ocsetup.exe.
+
_port_ is the TCP port number that you have used for the WFA server during installation.
+
If you are specifying an IPv6 address, you must enclose it with square brackets.

. Double-click the wfa_ocsetup.exe file.
. Read the information in the setup wizard and click *Next*.
. Browse or type the OpenJDK location and click *Next*.
. Enter a user name and password to override the default credentials.
+
A new database user account is created with access to the DataFabric Manager 5.x database.
+
NOTE: If you do not create a user account, the default credentials are used. You must create a user account for security purposes.

. Click *Next* and review the results.
. Click *Next*, and then click *Finish* to complete the wizard.
