---
permalink: workflows/task_import_oncommand_workflow_automation_content.html
sidebar: sidebar
keywords: import, user-created, oncommand, workflow, automation, content, finders, commands, export, installation, downloaded, storage, community, pack, data, pwershell, toolkits, perl
summary: "You can import user-created OnCommand Workflow Automation (WFA) content such as workflows, finders, and commands. You can also import content that is exported from another WFA installation, content that is downloaded from the Storage Automation Store or the WFA community, as well as packs, including Data ONTAP PowerShell toolkits and Perl NMSDK toolkits."
---
= Import OnCommand Workflow Automation content
:icons: font
:imagesdir: ../media/

[.lead]
You can import user-created OnCommand Workflow Automation (WFA) content such as workflows, finders, and commands. You can also import content that is exported from another WFA installation, content that is downloaded from the Storage Automation Store or the WFA community, as well as packs, including Data ONTAP PowerShell toolkits and Perl NMSDK toolkits.

== What you'll need

* You must have access to the WFA content that you want to import.
* The content that you want to import must have been created on a system that is running the same version or an earlier version of WFA.
+
For example, if you are running WFA 2.2, you cannot import content that was created using WFA 3.0.

* You can import content developed on N-2 versions of WFA only into WFA 5.1.
* If the `.dar` file references NetApp-certified content, the NetApp-certified content packs must be imported.
+
The NetApp-certified content packs can be downloaded from the Storage Automation Store. You must refer to the documentation of the pack to verify that all requirements are met.

*Steps*

. Log in to WFA through a web browser.
. Click *Settings*, and under *Maintenance* click *Import Workflows*.
. Click *Choose File* to select the `.dar` file that you want to import, and then click *Import*.
. In the *Import Success* dialog box, click *OK*.
